import { DraggableWindow } from "./draggable-window.jsx";

export function LightingWindow({ position, onPositionChange, onClose, gpuLightPass, onGpuLightPassChange, playerGpuShadowBleedRange, onPlayerGpuShadowBleedRangeChange, torchLightingLabel, onTorchLightingChange, torchShadowLabel, onTorchShadowChange, playerLightingLabel, onPlayerLightingChange, playerShadowLabel, onPlayerShadowChange, overgroundAmbient, undergroundAmbient, onOvergroundAmbientChange, onUndergroundAmbientChange, onShowTooltip, onHideTooltip, SettingTooltipTarget, settingsHelp, ambientStep, getWindowPosition, showCloseButton = true, showBackdrop = true, closeOnBackdropClick = true }) {
  const tip = (description, child) => <SettingTooltipTarget description={description} onShow={onShowTooltip} onHide={onHideTooltip}>{child}</SettingTooltipTarget>;
  return <DraggableWindow id="lighting_window" title="Lighting" position={position} onPositionChange={onPositionChange} onClose={onClose} getWindowPosition={getWindowPosition} showCloseButton={showCloseButton} showBackdrop={showBackdrop} closeOnBackdropClick={closeOnBackdropClick}>
    <div id="ambient_overground_control" className="corner_body zoom_control" aria-label="Ambient Overground"><span>Ambient Overground</span>{tip(settingsHelp.ambientIncrease, <button type="button" aria-label="Increase Overground ambient light" aria-description={settingsHelp.ambientIncrease} onClick={() => onOvergroundAmbientChange(ambientStep)} disabled={overgroundAmbient >= 1}>+</button>)}<span aria-live="polite">{overgroundAmbient.toFixed(1)}</span>{tip(settingsHelp.ambientDecrease, <button type="button" aria-label="Decrease Overground ambient light" aria-description={settingsHelp.ambientDecrease} onClick={() => onOvergroundAmbientChange(-ambientStep)} disabled={overgroundAmbient <= 0}>-</button>)}</div>
    <div id="ambient_underground_control" className="corner_body zoom_control" aria-label="Ambient Underground"><span>Ambient Underground</span><button type="button" onClick={() => onUndergroundAmbientChange(ambientStep)}>+</button><span>{undergroundAmbient.toFixed(1)}</span><button type="button" onClick={() => onUndergroundAmbientChange(-ambientStep)}>-</button></div>
    {tip(settingsHelp.gpuLightPass, <button id="gpu_light_pass_toggle" className="corner_body settings_option" type="button" aria-pressed={gpuLightPass} aria-label="GPU Light Pass" aria-description={settingsHelp.gpuLightPass} tabIndex={-1} onClick={onGpuLightPassChange}><span>GPU Light Pass</span><span id="gpu_light_pass_checkbox" aria-hidden="true">{gpuLightPass ? "☑" : "☐"}</span></button>)}
    {tip(settingsHelp.playerLighting, <button id="lighting_player_toggle" className="corner_body settings_option" type="button" aria-label="Cycle player lighting" aria-description={settingsHelp.playerLighting} tabIndex={-1} onClick={onPlayerLightingChange}>{playerLightingLabel}</button>)}
    {tip(settingsHelp.playerGpuShadowBleedRange, <button id="player_gpu_shadow_bleed_range" className="corner_body settings_option" type="button" aria-label="Player GPU Shadow Bleed Range" aria-description={settingsHelp.playerGpuShadowBleedRange} tabIndex={-1} onClick={onPlayerGpuShadowBleedRangeChange}>Player GPU Shadow Bleed Range ({playerGpuShadowBleedRange})</button>)}
    {tip(settingsHelp.playerShadow, <button id="shadow_player_toggle" className="corner_body settings_option" type="button" aria-label="Cycle player shadow" aria-description={settingsHelp.playerShadow} tabIndex={-1} onClick={onPlayerShadowChange}>{playerShadowLabel}</button>)}
    {tip(settingsHelp.torchLighting, <button id="lighting_torch_toggle" className="corner_body settings_option" type="button" aria-label="Cycle torch lighting" aria-description={settingsHelp.torchLighting} tabIndex={-1} onClick={onTorchLightingChange}>{torchLightingLabel}</button>)}
    {tip(settingsHelp.torchShadow, <button id="shadow_torch_toggle" className="corner_body settings_option" type="button" aria-label="Cycle torch shadow" aria-description={settingsHelp.torchShadow} tabIndex={-1} onClick={onTorchShadowChange}>{torchShadowLabel}</button>)}
  </DraggableWindow>;
}
