import { useLayoutEffect, useRef } from "react";
import { WindowBackdrop } from "./tutorial-windows.jsx";

export function LightingWindow({ position, onPositionChange, onClose, gpuLightPass, onGpuLightPassChange, playerGpuShadowBleedRange, onPlayerGpuShadowBleedRangeChange, torchLightingLabel, onTorchLightingChange, torchShadowLabel, onTorchShadowChange, playerLightingLabel, onPlayerLightingChange, playerShadowLabel, onPlayerShadowChange, overgroundAmbient, undergroundAmbient, onOvergroundAmbientChange, onUndergroundAmbientChange, onShowTooltip, onHideTooltip, SettingTooltipTarget, settingsHelp, ambientStep, getWindowPosition, showCloseButton = true, showBackdrop = true, closeOnBackdropClick = true }) {
  const windowRef = useRef(null);
  const dragStartRef = useRef(null);
  const clampPosition = (nextPosition) => { const rect = windowRef.current?.getBoundingClientRect(); return getWindowPosition(nextPosition, { width: rect?.width ?? 360, height: rect?.height ?? 320 }); };
  useLayoutEffect(() => { const keepWindowReachable = () => onPositionChange((currentPosition) => clampPosition(currentPosition)); keepWindowReachable(); window.addEventListener("resize", keepWindowReachable); return () => window.removeEventListener("resize", keepWindowReachable); }, []);
  const beginDrag = (event) => { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); dragStartRef.current = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, position }; };
  const moveDrag = (event) => { const drag = dragStartRef.current; if (!drag || drag.pointerId !== event.pointerId) return; onPositionChange(clampPosition({ left: drag.position.left + event.clientX - drag.x, top: drag.position.top + event.clientY - drag.y })); };
  const endDrag = (event) => { if (dragStartRef.current?.pointerId === event.pointerId) dragStartRef.current = null; };
  const tip = (description, child) => <SettingTooltipTarget description={description} onShow={onShowTooltip} onHide={onHideTooltip}>{child}</SettingTooltipTarget>;
  return <><WindowBackdrop visible={showBackdrop} closesOnClick={closeOnBackdropClick} onClose={onClose} /><section ref={windowRef} id="lighting_window" className="lighting_window" aria-labelledby="lighting_window_title" style={position} onClick={(event) => event.stopPropagation()}><div className="lighting_window_titlebar" onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onLostPointerCapture={endDrag}><div id="lighting_window_title" className="corner_title">Lighting</div>{showCloseButton ? <button className="corner_body settings_option lighting_window_close" type="button" aria-label="Close Lighting" tabIndex={-1} onPointerDown={(event) => event.stopPropagation()} onClick={onClose}>X</button> : null}</div><div className="lighting_window_body">
    <div id="ambient_overground_control" className="corner_body zoom_control" aria-label="Ambient Overground"><span>Ambient Overground</span>{tip(settingsHelp.ambientIncrease, <button type="button" aria-label="Increase Overground ambient light" aria-description={settingsHelp.ambientIncrease} onClick={() => onOvergroundAmbientChange(ambientStep)} disabled={overgroundAmbient >= 1}>+</button>)}<span aria-live="polite">{overgroundAmbient.toFixed(1)}</span>{tip(settingsHelp.ambientDecrease, <button type="button" aria-label="Decrease Overground ambient light" aria-description={settingsHelp.ambientDecrease} onClick={() => onOvergroundAmbientChange(-ambientStep)} disabled={overgroundAmbient <= 0}>-</button>)}</div>
    <div id="ambient_underground_control" className="corner_body zoom_control" aria-label="Ambient Underground"><span>Ambient Underground</span><button type="button" onClick={() => onUndergroundAmbientChange(ambientStep)}>+</button><span>{undergroundAmbient.toFixed(1)}</span><button type="button" onClick={() => onUndergroundAmbientChange(-ambientStep)}>-</button></div>
    {tip(settingsHelp.gpuLightPass, <button id="gpu_light_pass_toggle" className="corner_body settings_option" type="button" aria-pressed={gpuLightPass} aria-label="GPU Light Pass" aria-description={settingsHelp.gpuLightPass} tabIndex={-1} onClick={onGpuLightPassChange}><span>GPU Light Pass</span><span id="gpu_light_pass_checkbox" aria-hidden="true">{gpuLightPass ? "☑" : "☐"}</span></button>)}
    {tip(settingsHelp.playerLighting, <button id="lighting_player_toggle" className="corner_body settings_option" type="button" aria-label="Cycle player lighting" aria-description={settingsHelp.playerLighting} tabIndex={-1} onClick={onPlayerLightingChange}>{playerLightingLabel}</button>)}
    {tip(settingsHelp.playerGpuShadowBleedRange, <button id="player_gpu_shadow_bleed_range" className="corner_body settings_option" type="button" aria-label="Player GPU Shadow Bleed Range" aria-description={settingsHelp.playerGpuShadowBleedRange} tabIndex={-1} onClick={onPlayerGpuShadowBleedRangeChange}>Player GPU Shadow Bleed Range ({playerGpuShadowBleedRange})</button>)}
    {tip(settingsHelp.playerShadow, <button id="shadow_player_toggle" className="corner_body settings_option" type="button" aria-label="Cycle player shadow" aria-description={settingsHelp.playerShadow} tabIndex={-1} onClick={onPlayerShadowChange}>{playerShadowLabel}</button>)}
    {tip(settingsHelp.torchLighting, <button id="lighting_torch_toggle" className="corner_body settings_option" type="button" aria-label="Cycle torch lighting" aria-description={settingsHelp.torchLighting} tabIndex={-1} onClick={onTorchLightingChange}>{torchLightingLabel}</button>)}
    {tip(settingsHelp.torchShadow, <button id="shadow_torch_toggle" className="corner_body settings_option" type="button" aria-label="Cycle torch shadow" aria-description={settingsHelp.torchShadow} tabIndex={-1} onClick={onTorchShadowChange}>{torchShadowLabel}</button>)}
  </div></section></>;
}
